-- Execute este script no SQL Editor do projeto Supabase.

CREATE TABLE IF NOT EXISTS public.avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL CHECK (char_length(btrim(nome)) BETWEEN 1 AND 120),
    nome_projeto TEXT NOT NULL CHECK (char_length(btrim(nome_projeto)) BETWEEN 1 AND 160),
    descricao TEXT NOT NULL CHECK (char_length(btrim(descricao)) BETWEEN 1 AND 5000),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL CHECK (char_length(btrim(nome)) BETWEEN 1 AND 120),
    email TEXT NOT NULL CHECK (
        char_length(btrim(email)) BETWEEN 3 AND 254
        AND btrim(email) ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    ),
    mensagem TEXT NOT NULL CHECK (char_length(btrim(mensagem)) BETWEEN 1 AND 5000),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Migra o esquema antigo do projeto, que chamava a mensagem de "descricao"
-- e também possuía colunas legadas obrigatórias.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'contatos' AND column_name = 'descricao'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'contatos' AND column_name = 'mensagem'
        ) THEN
            ALTER TABLE public.contatos RENAME COLUMN descricao TO mensagem;
        ELSE
            ALTER TABLE public.contatos ALTER COLUMN descricao DROP NOT NULL;
        END IF;
    END IF;
END $$;

ALTER TABLE public.contatos ADD COLUMN IF NOT EXISTS mensagem TEXT;
ALTER TABLE public.contatos ADD COLUMN IF NOT EXISTS assunto TEXT;
ALTER TABLE public.contatos ALTER COLUMN assunto DROP NOT NULL;

ALTER TABLE public.avaliacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contatos ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.avaliacoes, public.contatos FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.avaliacoes, public.contatos TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.avaliacoes_id_seq, public.contatos_id_seq TO anon;

DROP POLICY IF EXISTS "Public can read reviews" ON public.avaliacoes;
DROP POLICY IF EXISTS "Public can submit reviews" ON public.avaliacoes;
DROP POLICY IF EXISTS "Public can delete reviews" ON public.avaliacoes;
CREATE POLICY "Public can read reviews"
    ON public.avaliacoes FOR SELECT TO anon USING (true);
CREATE POLICY "Public can submit reviews"
    ON public.avaliacoes FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public can delete reviews"
    ON public.avaliacoes FOR DELETE TO anon USING (true);

DROP POLICY IF EXISTS "Public can read contacts" ON public.contatos;
DROP POLICY IF EXISTS "Public can submit contacts" ON public.contatos;
DROP POLICY IF EXISTS "Public can delete contacts" ON public.contatos;
CREATE POLICY "Public can read contacts"
    ON public.contatos FOR SELECT TO anon USING (true);
CREATE POLICY "Public can submit contacts"
    ON public.contatos FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public can delete contacts"
    ON public.contatos FOR DELETE TO anon USING (true);
